package Enums;

public enum Signals {
    NOT_A_NUMBER,
    NOT_IMPLEMENTED,
    INCORRECT_INPUT,
    CHOOSE_SWIMMMER,
    CHOOSE_EDIT_OPTION,
    ASK_FOR_EDIT,
    INCORRECT_INPUT_BOOLEAN,
    INCORRECT_VARIABLE_TYPE,
    CHOOSE_SWIMMER,
    INVALID_INPUT
}
